### ISSUE TITLE
Unnecessary Equivalent Expansion Requirement

### ISSUE THREAD

**Issue by jmadridlarra** [PyProveIt/Prove-It#177] opened 2020-08-14 21:30 UTC
For some reason Prove-It is throwing an error when trying to instantiate a theorem with a Range of Ranges regarding an equivalent expansion.  Upon closer examination, we determined that this error should not be thrown in this case:

Theorem:
![image](https://user-images.githubusercontent.com/51240353/90293859-4ed4d400-de42-11ea-8cd5-7ea407acfef9.png)

Instantiation statement:
![image](https://user-images.githubusercontent.com/51240353/90293925-74fa7400-de42-11ea-9302-3c6427f6fb81.png)

Error:

```
ImproperReplacement: Improper replacement of (A_{1,1} MULTI_QUBIT_GATE R_{1,1}, ..A_{1,j} MULTI_QUBIT_GATE R_{1,j}.., A_{1,k} MULTI_QUBIT_GATE R_{1,k}, B_{1} MULTI_QUBIT_GATE S_{1}, C_{1,1} MULTI_QUBIT_GATE Q_{1,1}, ..C_{1,j} MULTI_QUBIT_GATE Q_{1,j}.., C_{1,h} MULTI_QUBIT_GATE Q_{1,h}), ..(A_{i,1} MULTI_QUBIT_GATE R_{i,1}, ..A_{i,j} MULTI_QUBIT_GATE R_{i,j}.., A_{i,k} MULTI_QUBIT_GATE R_{i,k}, B_{i} MULTI_QUBIT_GATE S_{i}, C_{i,1} MULTI_QUBIT_GATE Q_{i,1}, ..C_{i,j} MULTI_QUBIT_GATE Q_{i,j}.., C_{i,h} MULTI_QUBIT_GATE Q_{i,h}).., (A_{m,1} MULTI_QUBIT_GATE R_{m,1}, ..A_{m,j} MULTI_QUBIT_GATE R_{m,j}.., A_{m,k} MULTI_QUBIT_GATE R_{m,k}, B_{m} MULTI_QUBIT_GATE S_{m}, C_{m,1} MULTI_QUBIT_GATE Q_{m,1}, ..C_{m,j} MULTI_QUBIT_GATE Q_{m,j}.., C_{m,h} MULTI_QUBIT_GATE Q_{m,h}) via {h: 1, k: 1, m: 1, (A_{1,1}, ..A_{1,_b}.., A_{1,1}, ....A_{_a,1}, ..A_{_a,_b}.., A_{_a,1}...., A_{1,1}, ..A_{1,_b}.., A_{1,1}): (([GATE](H))), (B_{1}, ..B_{_a}.., B_{1}): (([GATE](Z))), (C_{1,1}, ..C_{1,_b}.., C_{1,1}, ....C_{_a,1}, ..C_{_a,_b}.., C_{_a,1}...., C_{1,1}, ..C_{1,_b}.., C_{1,1}): (([GATE](X))), (D_{1}, ..D_{_a}.., D_{1}): (([GATE](Z))), (S_{1}, ..S_{_a}.., S_{1}): ({}), (R_{1,1}, ..R_{1,_b}.., R_{1,1}, ....R_{_a,1}, ..R_{_a,_b}.., R_{_a,1}...., R_{1,1}, ..R_{1,_b}.., R_{1,1}): ({}), (Q_{1,1}, ..Q_{1,_b}.., Q_{1,1}, ....Q_{_a,1}, ..Q_{_a,_b}.., Q_{_a,1}...., Q_{1,1}, ..Q_{1,_b}.., Q_{1,1}): ({}), D: {(D_{1}, ..D_{_a}.., D_{1})}, A: {(A_{1,1}, ..A_{1,_b}.., A_{1,1}, ....A_{_a,1}, ..A_{_a,_b}.., A_{_a,1}...., A_{1,1}, ..A_{1,_b}.., A_{1,1})}, R: {(R_{1,1}, ..R_{1,_b}.., R_{1,1}, ....R_{_a,1}, ..R_{_a,_b}.., R_{_a,1}...., R_{1,1}, ..R_{1,_b}.., R_{1,1})}, B: {(B_{1}, ..B_{_a}.., B_{1})}, S: {(S_{1}, ..S_{_a}.., S_{1})}, C: {(C_{1,1}, ..C_{1,_b}.., C_{1,1}, ....C_{_a,1}, ..C_{_a,_b}.., C_{_a,1}...., C_{1,1}, ..C_{1,_b}.., C_{1,1})}, Q: {(Q_{1,1}, ..Q_{1,_b}.., Q_{1,1}, ....Q_{_a,1}, ..Q_{_a,_b}.., Q_{_a,1}...., Q_{1,1}, ..Q_{1,_b}.., Q_{1,1})}}:
```
```
Failure to expand (A_{1,1} MULTI_QUBIT_GATE R_{1,1}, ..A_{1,j} MULTI_QUBIT_GATE R_{1,j}.., A_{1,k} MULTI_QUBIT_GATE R_{1,k}, B_{1} MULTI_QUBIT_GATE S_{1}, C_{1,1} MULTI_QUBIT_GATE Q_{1,1}, ..C_{1,j} MULTI_QUBIT_GATE Q_{1,j}.., C_{1,h} MULTI_QUBIT_GATE Q_{1,h}), ..(A_{i,1} MULTI_QUBIT_GATE R_{i,1}, ..A_{i,j} MULTI_QUBIT_GATE R_{i,j}.., A_{i,k} MULTI_QUBIT_GATE R_{i,k}, B_{i} MULTI_QUBIT_GATE S_{i}, C_{i,1} MULTI_QUBIT_GATE Q_{i,1}, ..C_{i,j} MULTI_QUBIT_GATE Q_{i,j}.., C_{i,h} MULTI_QUBIT_GATE Q_{i,h}).., (A_{m,1} MULTI_QUBIT_GATE R_{m,1}, ..A_{m,j} MULTI_QUBIT_GATE R_{m,j}.., A_{m,k} MULTI_QUBIT_GATE R_{m,k}, B_{m} MULTI_QUBIT_GATE S_{m}, C_{m,1} MULTI_QUBIT_GATE Q_{m,1}, ..C_{m,j} MULTI_QUBIT_GATE Q_{m,j}.., C_{m,h} MULTI_QUBIT_GATE Q_{m,h}) because there is no explicit expansion for (Q_{i,j}, ..Q_{i,_a}.., Q_{i,j}).  The known expansions are for this variable are {(Q_{1,1}, ..Q_{1,_b}.., Q_{1,1}, ....Q_{_a,1}, ..Q_{_a,_b}.., Q_{_a,1}...., Q_{1,1}, ..Q_{1,_b}.., Q_{1,1}): ({})}.  (Note that multiple, equivalent expansion forms may be provided to fulfill this requirement).
```

Portion of interest from the error:
`because there is no explicit expansion for (Q_{i,j}, ..Q_{i,_a}.., Q_{i,j})`

For some reason Prove-It wants an expansion using the i and j indexes, however, these are only used internally in the theorem.

**Comment by wwitzel** [comment] 2020-08-16 17:23
Please commit and push your changes to "proveit.core_expr_types.expr_array.\_common\_" and anything else I need to reproduce this in the quantum demonstrations notebook.  Thanks.

**Comment by jmadridlarra** [comment] 2020-08-16 17:33
I just pushed my branch so everything should be reproducible.

**Comment by wwitzel** [comment] 2020-08-16 17:35
Thanks.  I just realized that I need to do a "--justessentials" rebuild.  So I suspect the problem was on my end.  Sorry.

**Comment by wwitzel** [comment] 2020-08-16 21:08
Why aren't S, R, and Q double-nested tuples like A, B, C, and D are?

**Comment by jmadridlarra** [comment] 2020-08-16 21:21
That's a good question.  I think it stems from the flattening process.  Originally, A, B, C, and D were some form of this: ExprTuple(ExprArray(ExprTuple(Gate(X)), ExprTuple(Gate(X)))).  However, during the flattening process the ExprArray() was removed to create a nested ExprTuple. (however, now that I'm looking back on it, I remembered that ExprArrays are technically ExprTuples so maybe we don't need the ExprTuple wrapping on an ExprArray?)  As a result of Prove-It's inability to count to ten, I ended up only doing one row of three elements resulting in A through D being doubly nested single elements. 

However, because S, R, and Q are the same for each MultiQubitGate, they don't need to be contained in an ExprArray() and can just be wrapped in an ExprTuple.  In the example we were testing on Friday, I don't think the nesting would be necessary.  However, my initial thought was that an ExprArray would flatten to an ExprTuple of ExprTuples (something like ExprTuple(ExprTuple(Gate(X)), ExprTuple(Gate(Y))), but now I'm thinking we would need to flatten the ExprArray completely (something like ExprTuple(Gate(x), Gate(Y)) regardless of which row the item is, correct? 

Does that answer your question?  I suspect most of this is legacy errors and I would most likely input things slightly differently now as a result of things I've learned while I was working on other branches so feel free to change and suggest new ways of doing things.

**Comment by wwitzel** [comment] 2020-08-16 21:34
I think the way it is supposed to be is that the variables with a single index should be assigned to non-nested ExprTuple's while the variables with two indices should be assigned to doubly-nested ExprTuples.  However, I can only seem to get past this error if I use a doubly-nested ExprTuple for S.  I can't quite figure that out.

**Comment by wwitzel** [comment] 2020-08-16 21:50
This simpler test does seem to work:
test = Forall ((h, k, m), Forall((varRange(B, one, m), 
                                                varRange(D, one, m), 
                                                varRange(S, one, m)),
            CircuitEquiv(
                        Circuit(ExprArray(ExprRange(i, ExprTuple(MultiQubitGate(indexed_var(B, i), indexed_var(S, i))), one, m))),
                        Circuit(ExprArray(ExprRange(i, ExprTuple(MultiQubitGate(indexed_var(D, i), indexed_var(S, i))), one, m)))
            )))

test.instantiate({h: one, k: one, m: one, 
                               B: ExprTuple(Gate(Z)), 
                               D: ExprTuple(Gate(Z)), 
                               S: ExprTuple(Set(one))}, assumptions=[test])

**Comment by jmadridlarra** [comment] 2020-08-16 21:51
Ah, ok that clears some things up.  I'll make a note that nested ExprRanges in the theorem should be instantiated with nested ExprTuples and single ExprRanges should be instantiated with ExprTuples.  

But that is odd that S needs to be a nested ExprTuple.  It might have something to do with the way MultiQubitGates are set up?  That's the only thing that I could think of off the top of my head, but after a quick look at the code, I don't see anything immediately obvious.  There is an auto_reduction method that might be doing some reductions that we don't want, but I think it's only set up for a set of one elements... not an empty Set().  On that note, what should a MultiQubitGate reduce to if it does contains an empty set?

**Comment by wwitzel** [comment] 2020-08-16 21:55
Perhaps the empty Set should be used when reducing to an "empty" grid location of the quantum circuit.

**Comment by jmadridlarra** [comment] 2020-08-16 21:59
Ah, ok.  "Empty" in the sense that it is just a wire (otherwise known as the identity operator)?  Or that there is actually nothing there, similar to the "SPACE" literal. 

Maybe we are having trouble with the original test case because the Set() is empty? Maybe it needs a single element like your simple test case.

**Comment by wwitzel** [comment] 2020-08-16 22:01
SPACE.  Indeed, it should not be empty, strictly speaking, but that wouldn't cause this particular error.  There is something else going on that I don't understand.

**Comment by wwitzel** [comment] 2020-08-16 22:21
There are a couple of screwy things going from instantiate to Lambda.apply to ExprRange.replaced_entries.  I don't think I will have this fixed by or on Monday.

**Comment by wwitzel** [comment] 2020-08-16 23:03
Basically, things work when you are just expanding a direct range of ranges, but if you are expanding a range of tuples of ranges, for example, it's not set up right.  So I'll need to think about this a little and hopefully have a solution "soon".

**Comment by wwitzel** [comment] 2022-11-19 19:51
Closing this older issue.  Much has changed and has been tested; I presume this issue has been addressed.

**Closed by wwitzel** 2022-11-19 19:51 UTC
Labels: bug
